name: SDS210_project
channels:
  - conda-forge

dependencies:
  # Core
  - python=3.12          
  - numpy
  - pandas
  - matplotlib

  - jupyterlab
  - ipykernel
  - jupyterlab_widgets

  - geopandas
  - rasterio




